# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [ python ]
        exclude: '.*/migrations/.*'
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [ python ]
        exclude: '.*/migrations/.*'
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [ python ]
        exclude: '.*/migrations/.*'
        args: [
            '--profile=black',
            '--project=app/',
            '--section-default=THIRDPARTY',
        ]
      - id: mypy
        name: mypy
        verbose: true
        require_serial: true
        entry: mypy
        language: system
        types: [ python ]
        exclude: '.*/migrations/.*|tests/pacts/.*|app/subscription/models.py|tests/app/subscription/services/test_subscription_date_helper.py'
