version: "3.9"

networks:
  service_network:
    driver: bridge

services:
  db:
    image: postgres:15.4
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - service_network

  service:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    image: django_python_service
    command: tail -F anything
    volumes:
      - ./app:/opt/django-python-service/app
      - ./translation:/opt/django-python-service/translation
      - ./tests:/opt/django-python-service/tests
      - ./pyproject.toml:/opt/django-python-service/pyproject.toml
      - ./poetry.lock:/opt/django-python-service/poetry.lock
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db
    networks:
      - service_network
