# Generated by Django 4.2.7 on 2024-09-04 11:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "translation_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.UUIDField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("original_content", models.TextField()),
                ("translated_content", models.TextField()),
                (
                    "format",
                    models.CharField(
                        choices=[("html", "HTML"), ("text", "Text")],
                        default="text",
                        max_length=4,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="translation",
            constraint=models.CheckConstraint(
                check=models.Q(("format__in", ["html", "text"])), name="format_valid"
            ),
        ),
    ]
