name: style and tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3

      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          max-line-length: "120"
          extend-ignore: "E203,W503"

  isort:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3

      - name: Run isort
        uses: isort/isort-action@v1
        with:
          configuration: "--profile black"
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run tests
        run: echo "test"
